---
title: "Get Help & Give Help!"
output:
  html_document:
    includes:
      in_header: header.html
editor_options: 
  chunk_output_type: console
---

When you have a problem in R:

1. Read the documentation: use `?` or, equivalently, `help`.
2. Google it (someone probably already had the same problem and someone else probably told him a way to fix it, probably on [StackOverflow](https://stackoverflow.com/)).
3. Ask it on Stack Overflow (SO) after checking that your question has not already been asked.
4. Come to one of our working sessions to get help and give help about R code. During these sessions, one could help you to post your first question on SO.

Some guidelines and resources are available at [SO](https://stackoverflow.com/tags/r/info).

We also propose to reference all the unanswered [r] questions of our members so that we can all answer them. For that, you just have to give your SO ID in your member infos. If you want to add one, please [email me](mailto::florian.prive@univ-grenoble-alpes.fr).

