---
title: "Other Resources"
output:
  html_document:
    includes:
      in_header: header.html
editor_options: 
  chunk_output_type: console
---

</br>

We are excited that you will be joining us for this workshop! Please fill out this [google form](https://docs.google.com/forms/d/e/1FAIpQLSd6yThLtJLjAICFzvOkPGoAou3aJcD-4s-7uhVFfQI3hVaoMQ/viewform?usp=sf_link) to let us know that you will be joining us. 

*Please click on the title to see the session description*

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, warning=FALSE, error = FALSE, message = FALSE)
library(tidyverse)
library(lubridate)
library(htmltools)
```

```{r}
PreMaterial <- data.frame(read_csv("./R Workshop Video Links.csv", col_names = FALSE))
names(PreMaterial)<-PreMaterial[2,]
PreMaterial<-PreMaterial[-c(1:3),]
PreMaterial<-PreMaterial[!(is.na(PreMaterial$Topic)),]
PreMaterial0 <- PreMaterial

# PreMaterial$NeedToKnow<-paste0("Importance Level: ",PreMaterial$`Importance Level`,";
#                                 Fun-ness: ", PreMaterial$`Fun-ness`, ";
#                                 Suggested For: ", PreMaterial$`Suggested for`)

# PreMaterial$NeedToKnow<-paste0('tags$li(tags$p("Importance Level: 
#                                ", PreMaterial$`Importance Level`))')
PreMaterial$NeedToKnow<-c(paste0("Importance Level: ",PreMaterial$`Importance Level`[1]), PreMaterial$`Importance Level`[-1])

PreMaterial$Notes<-gsub(pattern = '"', replacement = "'", x = PreMaterial$Notes)

# PreMaterial$Notes0<-paste0('tags$li(', #paste(
#                            paste0('tags$p("', PreMaterial$NeedToKnow, '"),'),
#                            ifelse(is.na(PreMaterial$Notes), "",
#                                   paste0('tags$p("', PreMaterial$Notes, '"),')),
#                            paste0('tags$a(href="', PreMaterial$`Video Link`, '", "Video Link"),
#                                   '),
#                            paste0('tags$a(href="', PreMaterial$Playlist, '", "Playlist Link")'),
#                            # collapse = ", "),
#                            ')')

# PreMaterial$Notes0<-paste0('tags$li(tags$p("Importance Level: ', PreMaterial$`Importance Level`,'")),
#                             tags$li(tags$p("Fun-ness: ', PreMaterial$`Fun-ness`, '")),
#                             tags$li(tags$p("Suggested For: ', PreMaterial$`Suggested for`, '")),',
#                             ifelse(is.na(PreMaterial$Notes), "",
#                                              paste0('
#                                              tags$li(tags$p("', PreMaterial$Notes, '")),
#                                              ')),
#                             'tags$li(tags$a(href="', PreMaterial$`Video Link`, '", "Video Link")),
#                             tags$li(tags$a(href="', PreMaterial$Playlist, '", "Playlist Link"))')

#',#'tags$p("Importance Level: ', PreMaterial$`Importance Level`,'"),

PreMaterial$Notes0<-paste0('tags$li(
                            tags$p("Fun-ness: ', PreMaterial$`Fun-ness`, '"),
                            tags$p("Suggested For: ', PreMaterial$`Suggested for`, '"),',
                            ifelse(is.na(PreMaterial$Notes), "",
                                             paste0('
                                             tags$p("', PreMaterial$Notes, '"),
                                             ')),
                            'tags$a(href="', PreMaterial$`Video Link`, '", "Video Link"),
                            tags$p(""),
                            tags$a(href="', PreMaterial$Playlist, '", "Playlist Link"))')

# PreMaterial$NeedToKnow<-""
PreMaterial$Title<-#paste0(PreMaterial$`Playlist Title`," - ", 
                          (PreMaterial$Topic)
PreMaterial$Authors<-"Aaron Mamula"
PreMaterial<-data.frame(PreMaterial)
rownames(PreMaterial)<-1:nrow(PreMaterial)
```

```{css}
.schedule {
  display: flex;
  justify-content: space-between;
  flex-wrap: wrap;
}

.limit {
  width: 100%;
  padding: 5px 0 5px 0;
}

.workshops-button {
  padding: 0.75em 1.25em;
  background-color: #cccccc;
  opacity: 0.9;
  width: auto;
  color: black;
  text-align: center;
  overflow: auto;
}

.workshops-button {
  padding: 0.75em 1.25em;
  background-color: #cccccc;
  opacity: 0.9;
  width: auto;
  color: black;
  text-align: center;
  overflow: auto;
}

.left-date {
  width: 20%;
  float: left;
  text-align: left;
}

.center-title {
  width: 60%;
  float: left;
  text-align: left;
  font-size: 120%;
}

.right-authors {
  width: 20%;
  float: right;
  text-align: right;
}

.workshops {
  margin: 1em 1em 0 0;
}

.active {
  background-color: #333333;
  color: whitesmoke;
}

```

```{js}
function main() {
  $('.schedule').hide();
  $('.schedule').fadeIn(2000);
  $('.workshops').hide();
  $('.workshops-button').on('click', function() {
    $(this).next().slideToggle(400);
    $(this).toggleClass('active');
  });
}
 
$(document).ready(main);
```

```{r}
counter<-3
```


## `r unique(PreMaterial$Playlist.Title)[counter] `

```{r}
program1<-PreMaterial[PreMaterial$Playlist.Title %in% unique(PreMaterial$Playlist.Title)[counter],]

div(
  class = "schedule",
  apply(program1, 1, function(event) {
    div(
      class = "limit",
      div(class = "workshops-button", 
          div(class = "left-date", 
              # (eval(parse(text=event[['NeedToKnow']])))),
              event[['NeedToKnow']]),
          div(class = "center-title", 
              # tags$i(event[['Title']])),
              tags$b(event[['Title']])),
          div(class = "right-authors",
              event[['Authors']])),
      tags$ul(class = "workshops",
              (eval(parse(text=event[["Notes0"]])) ) )
              # event[["Notes"]])
    )
  })
)

counter<-counter + 1
```

<br>


## `r unique(PreMaterial$Playlist.Title)[counter] `

```{r}
program1<-PreMaterial[PreMaterial$Playlist.Title %in% unique(PreMaterial$Playlist.Title)[counter],]

div(
  class = "schedule",
  apply(program1, 1, function(event) {
    div(
      class = "limit",
      div(class = "workshops-button", 
          div(class = "left-date", 
              # (eval(parse(text=event[['NeedToKnow']])))),
              event[['NeedToKnow']]),
          div(class = "center-title", 
              # tags$i(event[['Title']])),
              tags$b(event[['Title']])),
          div(class = "right-authors",
              event[['Authors']])),
      tags$ul(class = "workshops",
              (eval(parse(text=event[["Notes0"]])) ) )
              # event[["Notes"]])
    )
  })
)

counter<-counter + 1
```

<br>

